plugins {
    id "dev.architectury.loom-no-remap" version "1.17.491" apply false
    id "me.modmuss50.mod-publish-plugin" version "2.2.0" apply false
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.archives_base_name
    }
    version = "${rootProject.mod_version}.${System.getenv("GITHUB_RUN_NUMBER") ?: 9999}+mc${rootProject.minecraft_version}"
    group = rootProject.maven_group

    repositories {
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.caffeinemc.net/releases" }
        maven {
            name = "Rushmead"
            url = "https://mvn.imabad.dev/repository/maven-releases/"
        }
        maven { url "https://jitpack.io" }
        maven { url "https://api.modrinth.com/maven" }
        mavenCentral()
        mavenLocal()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
        withSourcesJar()
    }
}
