name: GitHub Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - uses: gradle/actions/wrapper-validation@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew :fabric:build --stacktrace
      - name: Publish to Modrinth
        if: ${{ env.MODRINTH_TOKEN != '' }}
        run: ./gradlew :fabric:publishModrinth --stacktrace
      - name: Publish to CurseForge
        if: ${{ env.CURSEFORGE_TOKEN != '' }}
        run: ./gradlew :fabric:publishCurseforge --stacktrace
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: fabric/build/libs/Theatrical-fabric-*.jar
